<link rel="stylesheet"
      href="${pageContext.request.contextPath}/statics/jquery-easyui-1.5.1/themes/default/easyui.css"/>
<link rel="stylesheet"
      href="${pageContext.request.contextPath}/statics/jquery-easyui-1.5.1/themes/icon.css"/>
<script type="application/javascript"
        src="${pageContext.request.contextPath}/statics/jquery-easyui-1.5.1/jquery.min.js"></script>
<script type="application/javascript"
        src="${pageContext.request.contextPath}/statics/jquery-easyui-1.5.1/jquery.easyui.min.js"></script>
<script type="application/javascript"
        src="${pageContext.request.contextPath}/statics/jquery-easyui-1.5.1/locale/easyui-lang-zh_CN.js"></script>
